-- AlterTable
ALTER TABLE "Match" ADD COLUMN     "phase" TEXT NOT NULL DEFAULT 'pool',
ADD COLUMN     "tour" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Pool" ADD COLUMN     "bronzeMatch" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "fightsPerPerson" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "phase" TEXT NOT NULL DEFAULT 'config';

-- AlterTable
ALTER TABLE "Round" ADD COLUMN     "penaltyA" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "penaltyB" INTEGER NOT NULL DEFAULT 0;
